# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
arr1 = np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [9]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones((2,5))
np.vstack((arr1,arr2)).astype(int)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [10]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones((2,5))
np.hstack((arr1,arr2)).astype(int)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [16]:
arr3 = np.arange(0,15).reshape(3,5)
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
arr4 = np.arange(0,15)
arr5 = arr4.reshape(3,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [23]:
arr6 = np.random.randint(1,7, size=(5, 5))
print("array 5x5 =", arr6)
print("Square of array =", np.square(arr6))

array 5x5 = [[6 1 4 1 3]
 [3 1 1 3 1]
 [5 1 2 1 6]
 [5 1 5 2 6]
 [3 5 4 2 2]]
Square of array = [[36  1 16  1  9]
 [ 9  1  1  9  1]
 [25  1  4  1 36]
 [25  1 25  4 36]
 [ 9 25 16  4  4]]


## Question:8

### Create 5x6 an array and find the mean?

In [24]:
arr7 = np.random.randint(2,8, size = (5, 6))
print("array 5x6 =", arr7)
print("Mean of array =", np.mean(arr7))

array 5x6 = [[3 3 5 4 4 7]
 [3 7 2 3 4 6]
 [5 5 7 3 3 4]
 [6 7 4 3 6 4]
 [4 2 2 5 2 6]]
Mean of array = 4.3


## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
sd = np.std(arr7)
print("Standard Deviation:", np.round(sd,3) )

Standard Deviation: 1.595


## Question:10

### Find the median of the previous array in Q8?

In [31]:
print("Median: ", np.median(arr7))

Median:  4.0


## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
print("Transpose: ", np.transpose(arr7))

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
arr8 = np.random.randint(5,9, size = (4, 4))
print(arr8)
print("sum of diagonal elements: ", np.trace(arr8))

[[5 7 8 5]
 [5 6 7 5]
 [7 7 6 7]
 [6 6 8 8]]
sum of diagonal elements:  25


## Question:13

### Find the determinant of the previous array in Q12?

In [35]:
determinant = np.linalg.det(arr8)
print("determinant: ", np.round(determinant,3))

determinant:  24.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [37]:
arr9 = np.random.randint(0,100,size=(4, 4))
print(arr9)
print("5th percentile : ", np.percentile(arr9, 5))
print("95th percentile : ", np.percentile(arr9, 95))

[[86  4 27 97]
 [73 44 35 65]
 [32 25 89 36]
 [67 32 55 25]]
5th percentile :  19.75
95th percentile :  91.0


## Question:15

### How to find if a given array has any null values?

In [38]:
array_null=np.array([0,2,3,4,5,6,7])
array_null = array_null.astype('float')
array_null[2]=np.NaN
print(array_null)
array_sum = np.sum(array_null)
array_has_nan = np.isnan(array_sum)
print(array_has_nan)


[ 0.  2. nan  4.  5.  6.  7.]
True
