# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
nulvec = np.zeros(10)
nulvec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
rangevec = np.arange(10,50)
rangevec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
rangevec.shape

(40,)

5. Print the type of the previous array in question 3

In [9]:
rangevec.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [12]:
print(np.__version__, np.show_config())

blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
1.19.2 None


7. Print the dimension of the array in question 3


In [13]:
rangevec.ndim

1

8. Create a boolean array with all the True values

In [15]:
boolarray = np.array(range(1, 10),dtype="bool" )
boolarray

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [21]:
aray2d = np.arange(0,4)
aray2d.reshape(2,2)



array([[0, 1],
       [2, 3]])

10. Create a three dimensional array



In [25]:
aray3d = np.arange(0,27).reshape(3,3,3)
aray3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [29]:
print ( "Stright = " ,rangevec)
print ( " reversed = ", rangevec[::-1])

Stright =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 reversed =  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [30]:
nulvec[5] = 1
nulvec

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [33]:
idenmat = np.identity(3) 
idenmat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [34]:
arr = np.array([1, 2, 3, 4, 5])
arrfloat = arr.astype(np.float32)
arrfloat

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                [7., 2., 12.]])
np.multiply(arr1,arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [36]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                [7., 2., 12.]])
print("arr1 > arr2") 
print(np.greater(arr1,arr2)) 
  
print("arr1 >= arr2") 
print(np.greater_equal(arr1,arr2)) 
  
print("arr1 < arr2") 
print(np.less(arr1,arr2)) 
  
print("arr1 <= arr2") 
print(np.less_equal(arr1,arr2)) 

arr1 > arr2
[[ True False  True]
 [False  True False]]
arr1 >= arr2
[[ True False  True]
 [False  True False]]
arr1 < arr2
[[False  True False]
 [ True False  True]]
arr1 <= arr2
[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [43]:
arayrange = np.arange(0,10)
oddarray = arayrange[arayrange % 2 == 1]
oddarray

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [45]:
arayrange[arayrange % 2 == 1] = -1
arayrange

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [51]:
arayrange[5:9]=12
arayrange

array([ 0, -1,  2, -1, 12, 12, 12, 12, 12, -1])

20. Create a 2d array with 1 on the border and 0 inside

In [52]:
arr = np.ones((3, 4))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [53]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[1, 1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [59]:
aray2d = np.arange(9).reshape(3, 3)
arr2dslice = aray2d[0]
arr2dslice

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [61]:
aray2d[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [64]:
aray2d[0:-1, -1]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [72]:
from numpy import random
arrayrandom = random.randint(100, size=(100)).reshape(10,10)
print (arrayrandom)
maxrand = np.amax(arrayrandom)
maxrand

[[71 65  6 44 23 58 14 83 78  6]
 [48 78 39 75 85  6 61 32 33 97]
 [57 79 71 47 30 54 74  5 23  9]
 [ 6 29 70 74 25 82 50 96 74 19]
 [80  1 35  4 31 67 11 87 39 85]
 [31 73 34 56 52 52 71  6 86 91]
 [ 0 21 48  3 82 36 11 61 29 48]
 [ 4  4 63 12 16 45 11 77 20  4]
 [ 7 37 67 77 51 79 78  9 93 66]
 [61 44 71 14 11 49 46 85 59 22]]


97

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']


array([[ 0.20384491,  1.48117909, -0.28731629,  1.45303743],
       [-0.01274925,  0.5108876 , -0.46394046,  1.03647469],
       [ 0.60888317,  0.55478944,  1.24865187,  0.16533618],
       [ 0.44204409, -0.09321278, -0.25010984, -0.1299433 ],
       [-0.54322527, -1.85820063,  1.12179252, -0.66112044]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [83]:
data[ (names == 'Bob') | (names == 'Will')]

array([[ 0.20384491,  1.48117909, -0.28731629,  1.45303743],
       [-0.54145798, -0.34651577,  0.38287693,  0.9146772 ],
       [ 0.60888317,  0.55478944,  1.24865187,  0.16533618],
       [ 1.19706626, -0.42914867, -1.90013645, -0.33079114]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [85]:
randarr2d = np.random.uniform(1,15, size=(5,3))
randarr2d

array([[ 5.37700594,  3.7381606 , 12.87909428],
       [14.99235283,  5.74508064, 10.85539314],
       [ 2.31085523,  9.1167068 ,  3.17157301],
       [10.62593162, 14.20081645,  3.79180293],
       [ 3.44617595, 12.4454016 , 10.72216474]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [86]:
randarr3d = np.random.uniform(1,16, size=(2,2,4))
randarr3d

array([[[ 3.75951873,  2.53268146,  8.96874736,  6.08500028],
        [ 7.70022972,  5.99768714,  9.11116806,  3.71363076]],

       [[ 4.88204338, 13.09492636,  2.3832591 ,  1.48413586],
        [ 9.53791421,  6.11943588,  5.0452028 ,  2.81259883]]])

33. Swap axes of the array you created in Question 32

In [89]:
np.swapaxes(randarr3d,1,2)

array([[[ 3.75951873,  7.70022972],
        [ 2.53268146,  5.99768714],
        [ 8.96874736,  9.11116806],
        [ 6.08500028,  3.71363076]],

       [[ 4.88204338,  9.53791421],
        [13.09492636,  6.11943588],
        [ 2.3832591 ,  5.0452028 ],
        [ 1.48413586,  2.81259883]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [95]:
array10 = np.arange(10)
arraysqrt = np.sqrt(array10)
arraysqrtrep = np.where(arraysqrt < 0.5 , 0, arraysqrt)
arraysqrtrep

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [104]:
arrayrandom01 = random.randint(100,size=(12))
arrayrandom02 = random.randint(100,size=(12))
print ("array01 = ", arrayrandom01)
print ("array02 = ", arrayrandom02)
np.maximum(arrayrandom01,arrayrandom02)


array01 =  [34 74  3 72 44  6  5 27 32 14 84 55]
array02 =  [20 33 78 91 60 53 34  2 37 88  6 96]


array([34, 74, 78, 91, 60, 53, 34, 27, 37, 88, 84, 96])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [108]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [112]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [113]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [114]:
arrayrandom03 = random.randint(100,size=(20))
np.cumsum(arrayrandom03)

array([  16,   87,  115,  165,  263,  344,  426,  490,  524,  596,  663,
        709,  792,  807,  855,  913,  995, 1015, 1024, 1078])